---
title: "Linear Regression"
author: "Ruolan Zeng"
output: pdf_document
---

## 1.Preprocessing

1.1 remove NA values
```{r}
data <- read.csv("https://github.com/lypf2018/HousePricesKaggle/raw/master/dataset/train.csv")
# View(data)
probNA <- function(x){
  sum(is.na(x))/nrow(data)
}
probNAcol <- apply(data, 2, probNA)
probNAcol[probNAcol>0.3]
```

In above 5 columns, there are many NA values, so we decided to remove these columns, Then remove all other NA values

```{r}
dim(data)
data[c("Alley","FireplaceQu","PoolQC","Fence","MiscFeature")] <- NULL
data["Id"] <- NULL
dim(data)
data <- na.omit(data)
dim(data)
sum(is.na(data))
# View(data)
```

## 

```{r}
require(MASS)
require(ISLR)
require(corrplot)

dataNum <- apply(data, 2, as.numeric)
dataNum <- as.data.frame(dataNum[,apply(dataNum, 2, function(x) !any(is.na(x)))])
```

```{r}
M <- cor(dataNum)
corrplot(M, method = "number")
```

```{r}
dim(dataNum)
dataNum[c("EnclosedPorch","MoSold","YrSold","X3SsnPorch","ScreenPorch","PoolArea","MiscVal","BsmtFinSF2"   ,"BsmtUnfSF","MSSubClass","OverallCond","LowQualFinSF")] <- NULL
dim(dataNum)
M <- cor(dataNum)
```

## 

```{r}
# Numbered correlation
corMat <- as.data.frame(corrplot(M,method = "number"))
names(corMat) <- names(dataNum)
# Find out which attributes have correlation of more than 50% with SalePrice
row.names(corMat)[abs(corMat$SalePrice) > 0.6]
```


```{r}
# analysis salePrice
summary(dataNum$SalePrice)
hist(dataNum$SalePrice)
# Deviate from the normal distribution.
# Have appreciable positive skewness.
# Show peakedness.
```

```{r}
# Relationship with numerical variables
lm.fit = lm(SalePrice~OverallQual, data = dataNum)
plot(lm.fit) 
summary(lm.fit) 
```

```{r}
plot(dataNum$OverallQual,dataNum$SalePrice)
#观察：小和大的房子少，中间大小的房子多。房子面积越大，价格越分散，有很贵的也有很便宜的，而中间大小的房子价格比较集中。这个图和上面那个图有什么关系？
abline(lm.fit,lwd = 2, col="red")
```

```{r}
plot(dataNum$GrLivArea, dataNum$SalePrice)
```

```{r}
lm.fit2 = lm(SalePrice~YearBuilt, data = dataNum)
plot(dataNum$YearBuilt, dataNum$SalePrice)
abline(lm.fit2,lwd = 2, col="red")
```

```{r}
lm.fit3 = lm(SalePrice~GarageCars, data = dataNum)
plot(dataNum$GarageCars, dataNum$SalePrice)
abline(lm.fit3,lwd = 2, col="red")
```

```{r}
lm.fit4 = lm(SalePrice~OverallQual+GarageCars, data = dataNum)
summary(lm.fit4)
plot(lm.fit4)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


